ASSERT_TIME = 180
GRAFT_RETRY_PERIOD = 3
JP_OVERRIDE_INTERVAL = 3.0
OVERRIDE_INTERVAL = 2.5
PROPAGATION_DELAY = 0.5
REFRESH_INTERVAL = 60  # State Refresh Interval
SOURCE_LIFETIME = 210
T_LIMIT = 210

ASSERT_CANCEL_METRIC = 0xFFFFFFFF